### ISSUE TITLE
Improve error message in focus search

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlrMBO#143]
We need a good error message here. The error occures in our focus search if the learner prediction returns NA / NaN / ... At the moment the error is:

Error in if (local.y < global.y) { : 
  missing value where TRUE/FALSE needed

(If needed I can make a litle code example later)

**Comment by berndbischl** [comment]
The thing is that this error should not happen anyhow.
(I have fixed multiple bugs regarding this already)

So the most important thing is a reproducible example.

**Comment by berndbischl** [comment]
But we can try to make the code more robust here and just count it as an "undesirable location".

But note that this will also "mask" real bugs here, to some extend in the model. 
So I am foremost curious WHY this happens, before we add a "catch-all" handling here.

**Comment by danielhorn** [comment]
Here is a minimal example with my NA-Learner.

library(mlrMBO)

makeRLearner.regr.test = function()
  makeRLearnerRegr(
    cl = "regr.test", package = "base",
    par.set = makeParamSet(), properties = c("numerics", "se"))

trainLearner.regr.test = function(.learner, .task, .subset, .weights = NULL, ...) 
  list(NULL)

predictLearner.regr.test = function(.learner, .model, .newdata, ...) {
  pred = runif(nrow(.newdata))
  pred.na = rep(NaN, nrow(.newdata))
  if(.learner$predict.type == "response")
    return(pred)
  else
    return(cbind(pred.na, se = pred.na))
}

lrn = makeLearner("regr.test", predict.type = "se")
fun = makeMBOFunction(function(x) x)
ps = makeNumericParamSet(len = 1, lower = 0, upper = 1)
ctrl = makeMBOControl(init.design.points = 8, iters = 1)

mbo(fun, ps, learner = lrn, control = ctrl)

**Comment by berndbischl** [comment]
Daniel,

1) 
thanks, that is a technically valid example. But my question was more like WHY does that happen in your case ;-)

2) 
Ok, but lets assume a for a moment that the model for some points during predictions breaks down and crashes. And lets also assume that the training of the model not completely failed, resulting in a "FailureModel". Because we already handle this.
What is our strategy now?

We just disregard these "bad" values during optimization? 
Do we warn about this?
And we hope that some (or better: many) points in search space exists where this does not happen? so we can still optimize?

**Comment by danielhorn** [comment]
Long story WHY that happened - to make it short: One of my master students used a linear regression modell of 3rd and 4th degree. Over all more than 10 coefficients had to be estimated in his model. He accidentally used only 10 points in his initial design. So, the training with lm worked (= did not generate an error), but some of the estimated coefficients were NA. And the prediction returned some NaNs.

**Comment by danielhorn** [comment]
The simplest strategy would be to return an error: "Your model crashed during the prediction". Or warn about it and propose random points in this situation.

**Comment by jakobbossek** [comment]
Why not offering both options via a parameter with the former being the default.

**Comment by berndbischl** [comment]
> The simplest strategy would be to return an error: "Your model crashed during the prediction". Or warn about it and propose random points in this situation.

Thats not so nice. Assume that NA happens for 0.1 % of points in search space. You would simply like "skip" these. And also we are not really concerned with "proposing random points" yet. We are still in the optimization phase. Assuming that we get predictions for some / enough points you just want to skip the bad ones.

If all points are NA, and we still dont have a FailureModel (which is kinda a strange case....) you might propose a random point then.

**Comment by danielhorn** [comment]
Of course: If there are only some NAs, we want to use something like na.omit. But probably still warn about it? My strategy was for the case, that we have only NAs.

Do we also have to distinguish the case: Model prediction is okay, but se prediction returned NAs? In this case we could switch from EI to Mean as infill crit. But, do we want a special handling for this case?

**Comment by PhilippPro** [comment]
I also got NA message in one of my iterations and the whole process crashed. I just want to mention, that this is a bit annoying especially after several hours of computation and then there is at the moment NO result at all, at least the process until the error should be saved in the `result` or NA's should be handled otherwise as mentioned before.

The error was:

`Fehler in evalTargetFun.OptState(opt.state, xs, extras) : 
  Objective function output must be a numeric of length 1, but we got: NaN`

**Comment by berndbischl** [comment]
@PhilippPro 
1) Have you looked up how to store intermediate results on disk? Have you turned that option on?

2) mbo does impute NA values in the target function output. can you also generate an example to reproduce this error?

**Comment by PhilippPro** [comment]
1) `save.on.disk.at` and `save.file.path` in `makeMBOControl; ok I did not know this, thx.

2) Does it (already)? I think this always happens if there is an NA value,

Example:

`> # Define the regression task
> data(airquality)
> # delete NA values
> airquality = airquality[!apply(is.na(airquality),1, function(x) any(x) ),]
> 
> # Define our target function
> # Measures: MSE
> performan = function(x)  {
+   pred <- ranger(formula = Ozone ~ . , data = airquality, mtry = x$mtry, min.node.size = x$min.node.size, 
+                  sample.fraction = x$sample.fraction, replace = x$replace, num.trees = 3000)$predictions
+  if(x$replace == TRUE) {
+     measureMSE(airquality$Ozone, pred)
+   } else {
+     NA
+   }
+ }
> 
> # Its ParamSet
> ps = makeParamSet(
+   makeLogicalParam("replace"),
+   makeNumericParam("sample.fraction", lower = 0.05, upper = 1),
+   makeDiscreteParam("min.node.size", values = 1:10),
+   makeDiscreteParam("mtry", values = 1:5)
+ )
> 
> # Budget
> f.evals = 40
> mbo.init.design.size = 30
> 
> # Focus search
> infill.opt = "focussearch"
> mbo.focussearch.points = 100
> mbo.focussearch.maxit = 3
> mbo.focussearch.restarts = 3
> 
> library(mlrMBO)
> # The final SMOOF objective function
> objFun = makeMultiObjectiveFunction(
+   name = "reg",
+   fn = performan,
+   par.set = ps,
+   has.simple.signature = FALSE,
+   noisy = TRUE,
+   n.objectives = 1,
+   minimize = c(TRUE)
+ )
> 
> # Build the control object
> method = "parego"
> if (method == "parego") {
+   mbo.prop.points = 1
+   mbo.crit = "cb"
+   parego.crit.cb.pi = 0.5
+ }
> 
> control = makeMBOControl(n.objectives = 1L, propose.points = mbo.prop.points)
> control = setMBOControlTermination(control, max.evals =  f.evals, iters = 300)
> control = setMBOControlInfill(control, crit = mbo.crit, opt = infill.opt,
+                               opt.focussearch.maxit = mbo.focussearch.maxit,
+                               opt.focussearch.points = mbo.focussearch.points,
+                               opt.restarts = mbo.focussearch.restarts,
+                               crit.cb.pi = parego.crit.cb.pi, crit.cb.lambda = NULL)
> 
> mbo.learner = makeLearner("regr.randomForest", predict.type = "se")
> 
> design = generateDesign(mbo.init.design.size, smoof::getParamSet(objFun), fun = lhs::maximinLHS)
> 
> set.seed(123)
> result = mbo(fun = objFun, design = design, learner = mbo.learner, control = control)
Computing y column(s) for design. Not provided.
[mbo] 0: replace=TRUE; sample.fraction=0.666; min.node.size=5; mtry=2 : y = 319 : 0.1 secs : initdesign
Fehler in evalTargetFun.OptState(opt.state, xs, extras) : 
  Objective function output must be a numeric of length 1, but we got: NA`

**Comment by danielhorn** [comment]
As for most things in MBO you have to enable the imputation by hand. For example. you have to set
`impute.y.fun = 1`
in `makeMBOControl` to impute every NA with a constant 1.

Both mechansim, the continue-mechanism and the imputation-mechanism, are describe on the help page
`?mlrMBO::error_handling`

**Comment by PhilippPro** [comment]
It must be a function not a fixed value, something like `impute.y.fun = function(x, y, opt.path) 1`

**Comment by ja-thomas** [comment]
I still don't really see a relevant/real reproducible example.

Everything should work with the imputation.


Please reopen when this happens again.
