### ISSUE TITLE
minimize = FALSE in example Run

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlrMBO#145]
Go to ex_1d_numeric and set minimize = FALSE in makeMBOControl. Now, for some reason, the negative model is plotted. Supposedly, there is a minus missing somewhere in the code ...

**Comment by danielhorn** [comment]
Thanks for fixing it! But I stumpled across the next ... bug?

I am maximizing and I am using the lcb. Now, in the lower plot in the example run the negative lcb is plotted - new points are proposed for minimal values of the plotted lcb. But I think we want the normal lcb here. If we want to maximize the target function, we also do want to maximize the lcb. Please correct me if I'm wrong ...

If we use the EI - we allways want to maximize the EI, right? But if we use the lcb, the optimization direction depends of the infill.crit depends on the optimization direction of the target function.

**Comment by berndbischl** [comment]
please never post report without a specific example we can look at

**Comment by berndbischl** [comment]
the code  I mean

**Comment by danielhorn** [comment]
I did not, since it is 99% the code from inst/examples/ex_1d_numeric. I just added minimize = FALSE and set crit = "lcb" ...

##### optimizing a simple sin(x) with mbo / EI #####

#library(mlrMBO)
library(ggplot2)
library(mlrMBO)
library(smoof)
configureMlr(show.learner.output = FALSE)
pause = interactive()
set.seed(1)

obj.fun = makeSingleObjectiveFunction(
  name = "Sine",
  fn = function(x) sin(x),
  par.set = makeNumericParamSet(lower = 3, upper = 13, len = 1),
  minimize = FALSE
)

ctrl = makeMBOControl(init.design.points = 6, propose.points = 1)
ctrl = setMBOControlTermination(ctrl, iters = 10L)
ctrl = setMBOControlInfill(ctrl, crit = "lcb", opt = "focussearch", opt.focussearch.points = 500L)

lrn = makeLearner("regr.km", predict.type = "se", covtype = "matern3_2")

run = exampleRun(obj.fun, global.opt = -1, learner = lrn,
  control = ctrl, points.per.dim = 100, show.info = TRUE)

plotExampleRun(run, pause = pause, densregion = TRUE)

**Comment by berndbischl** [comment]
I am reeoping now. We need to figure out what goes on here, then open up a clean precise issue.

**Comment by berndbischl** [comment]
I looked at this with JR. The bug and bad code is (at least) in 
    renderExampleRunPlotSingleCrit1d.R
lines 38 ff

there is a "hack" for the EI. that calculates a opt.direction -1, +1 multipliert.
that needs to be in a function, with lcb covered too

**Comment by danielhorn** [comment]
Actually, every of our infill.crits should be covered?

**Comment by jakob-r** [comment]
in `infill_crits.R`:
* every infill crit is designed to be minimized
* we could add an attribute to state if the infill_crit is orgignally supposed to be maximized (in literature)

Following thins we could access this attribute for plotting in `renderExampleRunPlotSingleCrit1d.R` etc.

Anyhow:
* The lcb is the lower confidence bound - if we turn it over it will be the *ucb*, hence the labelling would be wrong in the plot
* We definitly don't want a ucb in `infill_crits.R`
* We could fix it again with a dirty fix and just rename it in `renderExampleRunPlotSingleCrit1d.R`

**Comment by tobiaswagner** [comment]
How is the LCB implemented. It only makes sense to be applied to functions already transformed for minimization, as the name lower confidence bound is somehow related to a minimization. A maximization of the LCB  would penalize high standard deviations.

**Comment by berndbischl** [comment]
Ok, let the summarize the current status here. 

1) Implementation and optimization.
https://github.com/mlr-org/mlrMBO/blob/master/R/infill_crits.R

As one can see from that code the LCB as a technical infill crit also work if the orig. function f is maximized. you can see it here.

  maximize.mult * p$response - inflate * control$infill.crit.lcb.lambda * p$se

So for maximization we basically compute -UCB internally, and minimize that as infill, because our internal standard to minimize. so that does make sense, and everything is correct, right?

2) regarding the plot we now have these options:

a) multiply the lcb crit by minus 1, if we maximize. then we have not -UCB but UCB. 
problem is that the string "lcb" does not really match then what is displayed.
i am not sure i care soooo much about this.

b) leave it like it is. which i am not sure is better. because we still dont really display lcb. 
we display -UCB. and it already confused daniel.

c) do a), but also put in some code to change the string. which is going to be a bit annoying to do it properly.

My suggestion is a). we already have "multiplier code" for the EI, to display not -EI, what we compute internally. and just doc what happens for LCB if one maximizes. 
Is that OK?

**Comment by tobiaswagner** [comment]
Not that important, but in my SMS-EGO papers I replaced the term “LCB” by “potential solution” which is independent of the search direction.

**Comment by berndbischl** [comment]
“potential solution” : is that a standard term? 
I admit I never heard that before.

**Comment by berndbischl** [comment]
what if we get rid of the L? and just call it "confidence bound" = CB ?

**Comment by tobiaswagner** [comment]
I would agree. „Potential solution“ has not become a standard term, until now ;-)

**Comment by berndbischl** [comment]
of course my solutions are always best (jk).

so we get rid of one character, everywhere. 
and actually add the explanations from this thread to the docs. 
and multiply the new CB by -1 if we maximize, for the plots.

**Comment by berndbischl** [comment]
I opened 2 new clean issues, closing here
#169 
#168
