### ISSUE TITLE
the plots in ParamHelpers need to be reviewed

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#162]
these are plotOptPath and plotYTraces. We need to do that as a group
the currently are somewhat strange.

**Comment by berndbischl** [comment]
and then demoed in our examples.

**Comment by berndbischl** [comment]
the plots CURRENTLY are plotIOptPath and plotYTraces

**Comment by danielhorn** [comment]
What do you mean with "strange"? Karin and I worked on this a year ago. In the end, I think, you looked at the plots and gave us your okay. Otherwise we would not have stopped working on it. We should talk about it ...

The challenge with the plots was: They have to handle every kind of opt.path, includung: numeric params, discrete params, mixtures of both, Single Crit and Multi Crit with any dimension for both X and Y, single-point and multi-point proposals (even in Single-Point there may be multiple points for iteration 0 (initial design)). At the moment we can handle all of it.

**Comment by berndbischl** [comment]
Well I meant what I wrote: We should look at the, as a group and discuss whether they show us what we want. I am not even sure everybody knows they exist, so this cannot be a bad thing.

What I already noticed is this:
Assuming we multiple point with the same dob. This happens in multi-point. The Y-curve is averaged for for these points. 
But this does not make sense right? I am interested in the average core of my 3 points, but in their best value.

**Comment by danielhorn** [comment]
Sure, talking is never a bad thing, and I am open for new (better) ideas for some plots. I am 100% sure we did not found the best solution for every situation. Since there are so many different situations ... and relooking at the tests I already noticed a special case that does throw an error :(

This is in plotYTrace? You're probably right.

**Comment by berndbischl** [comment]
I thing it also appears in the plotOptPath. But like a said, lets get on hangout and look at it together.

**Comment by berndbischl** [comment]
They seem to be fine now. We can open issues when stuff looks bad
