### ISSUE TITLE
Blocking is blocking us....

### ISSUE THREAD

**Issue by joaquinvanschoren** [mlr-org/mlrMBO#213]
Hi, we have some blocked data with imbalanced classes. We're using nested resampling.

Of the bat, we find out that this leads to missing levels, MBO is not amused:

```
Could not predict with learner ModelMultiplexer: Error in checkPredictLearnerOutput(.learner, .model, p) : 
  predictLearner for ModelMultiplexer has returned not the class levels as column names: 3,9,4,2,6,8,5,7
```

Stratification to the rescue! Or not?

```
Blocking can currently not be mixed with stratification in resampling!
```

Help, what to do now? We can't just remove the small classes, unfortunately...

**Comment by berndbischl** [comment]
Your setup seems to be quite complicated, and I am unsure I understand all details from your short post.

> Of the bat, we find out that this leads to missing levels, MBO is not amused:

But the error message seems to show another problem? I seems to show that the return object of the learner is somehow encoded wrongly? (Maybe I am mistaken here and the cols are missing because some classes become empty in resampling?)

> Blocking can currently not be mixed with stratification in resampling!

Thats unfortunately true. How would YOU in general create the training tests sets for your case?

**Comment by joaquinvanschoren** [comment]
Indeed, what happens is that some classes become empty if you don't use stratification. Besides stratification, Is there another way we can avoid this?

Well, what you could do is sample entire blocks in a way that gives you a class distribution close to the original? Or alternatively, make sure that every fold would have at blocks that together cover all classes?

I also found this, but it seems that they have a different interpretation of strata: 
https://cran.r-project.org/web/packages/blockrand/blockrand.pdf

**Comment by joaquinvanschoren** [comment]
Ok for closing, but it would still be interested in a solution later on :)
