### ISSUE TITLE
Add early stopping to setMBOControlTerminations

### ISSUE THREAD

**Issue by DanielKuehn87** [mlr-org/mlrMBO#264]
Terminate, if estimated global optimum does not improve (by x percent / by value x) within the next n evals. (basically like early_stopping_rounds in xgboost).

**Comment by ja-thomas** [comment]
Does that make sense for mbo? Since we do a lot of exploration it can happen that in early stages of the algorithm the global optimum will not improve for quite some time.

**Comment by jakob-r** [comment]
I can understand the motivation behind that criteria but it certainly can lead to stopping too early for the reason @ja-thomas gave and I want to add that for some problems it is hard to say when the "early stage" is over. 

Another similar approach to stop, which is slightly better, is to stop if the expected improvement stays below a certain threshold for a while. This is nice because it combines the improvement of the global optimum with the possible improvement through exploration.

We should only implement stopping methods that are well established in the MBO literature. 

However, thanks to @jakobbossek it is now easy to add custom stopping criteria. He also added an example in the Helppage of `?setMBOControlTermination`.

**Comment by jakobbossek** [comment]
I agree with @ja-thomas and @jakob-r. Creating you own termination condition is quite easy:
```splus
makeMyMBOTermination = function(params) {
  ...
  function(opt.state) {
    # extract your information from the opt.path in the opt.state object
   ...
    return(list(
      term = term, # logical indicating if the stopping condition is met
      message = message, # character message describing the stopping condition
      code = "term.cond")) # short code with prefix "time."
  }
}
```

**Comment by jakob-r** [comment]
@jakobbossek I edited your code because atm we just allow "term.custom" as a code (see `getOptStateValidTerminationStates()`). If you want to change that open an issue.

**Comment by jakobbossek** [comment]
I think we can close here.
