### ISSUE TITLE
Infill curve in exampleRuns

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#330]
I guess our original intention was to always maximize the infill criteria.
This should be reflected in the example Run plots.

Unfortunately it happened numerous times that we changed that or spotted one plot where it is still wrong.
This is because i.e. for minimization the CB looks more intuitive if it corresponds to the function that we want to minimize. 
But if you give a talk about MBO and this example comes up it becomes difficult because you talked about maximizing the infill. 

So we should come to a final decision or put an option into the plot function.

**Comment by berndbischl** [comment]
> I guess our original intention was to always maximize the infill criteria.

thats wrong. and that was always documented in the header of infillcrits.R
there we said that we wanted to MINIMIZE each crit. 

now if you are talking about visualization and plots:
i am not sure if we ever formally defined this, but the idea was to "naturally" show the crits as they are. 
which is the reason for, if you look at the plotting code now, you see some ugly if-statements that say:
"if EI, multiply with -1, as we internally compute -EI(x), because like I said, we always minimize.

ALL of these problems now hopefully are totally resolved due to @jakobbossek, and his cool refactoring of the InfillCrits.

Can you make more precise what you mean? Or post an example where something is still wrong?
Please note that I totally agree with this:

> This is because i.e. for minimization the CB looks more intuitive if it corresponds to the function that we want to minimize.

And I dont want to show -EI(x) in talks, I want to show EI(x).

**Comment by jakob-r** [comment]
Dang! Was not speaking clearly enough. Internally we minimize - yes. 
In some talks however we say that the proposed point is the argmax of the infill. This then conflicts when the same talk shows the LCB.

**Comment by jakob-r** [comment]
Solved with https://github.com/mlr-org/mlrMBO/pull/343
