### ISSUE TITLE
Handling constraints

### ISSUE THREAD

**Issue by sfeuerriegel** [mlr-org/mlrMBO#389]
Hi everyone,

I was trying to get the mlrMBO running in a small sandbox example together with constraints. Unfortunately, I doesn't seem to work successfully. Does any one have a recommendation? 

Here's a small example:
```
obj_fun <- makeCosineMixtureFunction(1)
obj_fun <- convertToMinimization(obj_fun)

obj_fun_constraint <- makeSingleObjectiveFunction(
  name = "simple_example",
  fn = obj_fun,
  constraint.fn = function(x) {
    return(x < 0.5)
  },
  par.set = attr(obj_fun, "par.set"),
  minimize = TRUE
)


ggplot2::autoplot(obj_fun_constraint)

design <- generateDesign(n = 5, par.set = getParamSet(obj_fun_constraint), fun = lhs::randomLHS)
design$y <- apply(design, 1, obj_fun_constraint)

surrogate <- makeLearner("regr.km", predict.type = "se", covtype = "matern3_2", control = list(trace = FALSE))

control <- makeMBOControl()
control <- setMBOControlTermination(control, iters = 10)
control <- setMBOControlInfill(control, crit = makeMBOInfillCritEI())

result <- mbo(obj_fun_constraint, design = design, learner = surrogate, control = control, show.info = TRUE)
print(result)

run <- exampleRun(obj_fun_constraint, learner = surrogate, control = control, show.info = FALSE)
print(run)

plotExampleRun(run, iters = c(1L, 2L, 10L), pause = FALSE)
```

Thank you all. Your time and effort is highly appreciated!

**Comment by jakobbossek** [comment]
Hi, non-box-constraints specified via `constraint.fn` in smoof are not yet supported by mlrMBO. However, since your example simply defines an upper box-constraint you could modify the cosine-mixture function:
```r
obj_fun_constraint = makeCosineMixtureFunction(1)
attr(obj_fun_constraint, "par.set")$pars$x$upper = 0.5
obj_fun_constraint = convertToMinimization(obj_fun_constraint)
...
```

**Comment by jakob-r** [comment]
We should probably integrate a usefull error message in `mlrMBO` and can you (@jakobbossek) check, that the user is suggested to define such simple constraints in the ParamSet instead of `constraint.fn` in the documentation of `makeSingleObjectiveFunction`?

**Comment by jakobbossek** [comment]
@jakob-r The docs of the `constraint.fn` parameter of `make{Single,Multi}ObjectiveFunction` already states: Function which returns a logical vector indicating whether certain conditions are met or not. Default is \code{NULL}, which means, that there are no constraint beside possible box constraints defined via the \code{par.set} argument.

+1 for error message in mlrMBO

**Comment by danielhorn** [comment]
Actually, we do have some kind of constraint handling, however, you can not use the constraints from smoof to enable it.

The objective function should return an NA in the forbidden areas, and the correct objective value in the allowed area. Now you can use the impute.y.fun argument of makeMBOControl to replace the NA with a different value. You should choose a (mostly) constant, undesired value for this. For example: If you know that your objective function is in [0, 1], you can use 2 as a constant value for the imputation. This high value indicates that the area is bad (it is, since it is forbidden), and the EI should focus on allowed areas, in the long term.

We used this in one of my papers, however, it is mostly experimental at the moment.
