### ISSUE TITLE
Website links itself via Documentation link

### ISSUE THREAD

**Issue by theGreatWhiteShark** [mlr-org/mlrMBO#460]
In http://mlrmbo.mlr-org.com/ when you hit the *Documentation* link right at the top of the document you get redirected to the very same page. Is this intended?

I would suggest to link to HTML version of the manual hosted via CRAN instead. https://cran.r-project.org/web/packages/mlrMBO/mlrMBO.pdf
Also the vignette is a great help and should be linked there too https://cran.r-project.org/web/packages/mlrMBO/vignettes/mlrMBO.html

**Comment by jakob-r** [comment]
It's because the README is used to generate the start page. 
If you are on the [page](http://mlrmbo.mlr-org.com/ ) and click on Quickstart you'll arrive to the Vignette. So it is all there. Maybe not in the most obvious way, though. I will look into it when I have time but as it's nothing serious I will close this issue.
Thanks for your input.
